/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_justfortest_BspatchUtils */

#ifndef _Included_com_example_justfortest_BspatchUtils
#define _Included_com_example_justfortest_BspatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_justfortest_BspatchUtils
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_justfortest_BspatchUtils_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
